### ISSUE TITLE
Got a 404 error on PDF / Images download link generation

### ISSUE THREAD

**Issue by K31Z0** [enupal/snapshot#10]
### Description
Got a 404 error on PDF / Images download link generation:

```
HTTP 404 – Not Found – yii\web\NotFoundHttpException
Template not found: enupalsnapshot/my-first.pdf
```

I'm maybe missing something to make it work.

### Steps to reproduce

1. Install the extension
2. Copy / Paste the example code in your template
```
{%  set settings = {
        filename: 'my-first-image.png',
        asImage: true
    }
%}

{% set url = craft.enupalsnapshot.displayHtml("<h1>Hello world!</h1>", settings) %}

<a target="_blank" href="{{url}}"> Download Image</a>
```
3. The URL generated is always `http://mydomain.test/enupalsnapshot/my-first-image.png`

### Additional info

- Craft version: Craft Pro 3.0.30.1
- PHP version: 7.0.32
- Database driver & version: MySQL 5.7.21
- Plugin version: 1.0.6

**Comment by andrelopez** [comment]
Hi @K31Z0 

This could be due to a permissions issue. Could you please check that the `enupalsnapshot` exists in your web (public) folder and has the right permissions?

Best,

**Comment by K31Z0** [comment]
Hi @andrelopez,

Yes the `enupalsnapshot` exists in the public folder (screen attached)
I also tried to change to rights to 777 but nothing change.

[
![screen shot 2018-11-08 at 18 56 07](https://user-images.githubusercontent.com/1470129/48218137-7bb0a900-e389-11e8-80b1-e90bdf7b5b73.png)
![screen shot 2018-11-08 at 18 54 31](https://user-images.githubusercontent.com/1470129/48218138-7bb0a900-e389-11e8-9b8f-836848c4dadb.png)

](url)

**Comment by andrelopez** [comment]
Thanks @K31Z0,

Thanks for following up. Can you see the image in the enupalsnapshot folder?

It is weird because the error says that Template not found: `enupalsnapshot/my-first.pdf` however the url is pointing to a `my-first.png` image

Could you please send me a screenshot when you visit: http://mydomain.test/enupalsnapshot/my-first-image.png in your browser?

_You can send us files to support@enupal.com_

Best,

**Comment by K31Z0** [comment]
Hi @andrelopez,

I cannot see the picture in the snapshot folder.

Yes sorry, the example in the ticket title was with a PDF test, but the behaviour is the same for the pictures.

The screenshot will follow in your email

Best.

**Comment by andrelopez** [comment]
@K31Z0  We'll try to improve this behavior by adding support to store the pdf via asset folders.

Please subscribe to this ticket: https://github.com/enupal/snapshot/issues/2

**Comment by K31Z0** [comment]
Dear Andre,

Sorry for the late response.
Just replying to let you know that with the recent updates and Craft 3.1 everything works fine now :)

Best regards

Luigi
