### ISSUE TITLE
File not Found

### ISSUE THREAD

**Issue by fdghffdgf** [enupal/snapshot#11]
I tried to install wkhtmltopdf on my mac via the Installer and via Brew. 
The Error i get:
`Something went wrong when creating the PDF file: The exit status code '127' says something went wrong: stderr: "sh: 1: /usr/local/bin/wkhtmltopdf: not found " stdout: "" command: "/usr/local/bin/wkhtmltopdf" --lowquality --dpi '96' --load-error-handling 'ignore' --zoom '1.33' '/homepages/21/d456848011/htdocs/craft/storage/runtime/temp/enupalsnapshottemp/knp_snappy5c13c069de75f0.40538250.html' '/homepages/21/d456848011/htdocs/craft/web/enupalsnapshot/aquafun_x0hlIbTNBl.pdf'.
`

I can see and open wkhtmltopdf - what did i wrong? I'm really not the best at serverside settings.

Thanks for any help

**Comment by andrelopez** [comment]
Hi @fdghffdgf 

Could you please run the next command in your terminal:
`which wkhtmltopdf`

What is the output?

**Comment by fdghffdgf** [comment]
/usr/local/bin/wkhtmltopdf

**Comment by andrelopez** [comment]
Thanks @fdghffdgf 

Could you pelase go to The Snapshot Settings in your Craft CMS dashboard and save the next paths:

- wkhtmltopdf
`/usr/bin/wkhtmltopdf`

- wkhtmltoimage
`/usr/bin/wkhtmltoimage` 

After the save the new paths, did you see a blue confirmation message?

**Comment by fdghffdgf** [comment]
I get the same error like before: 

> Something went wrong in the test. Please check the path and your logs.

 Logs says the same like above.

**Comment by andrelopez** [comment]
Sorry @fdghffdgf I haven't tested in MAC, could you please try to install wkhtmltopdf from this link: https://wkhtmltopdf.org/downloads.html#stable

**Comment by fdghffdgf** [comment]
Hm… This was the first what i tried, after that brew.

**Comment by andrelopez** [comment]
Ok, let's try the next instructions:

- Could you please run the next command in the console?
`wkhtmltopdf https://google.com google.pdf` 

- If you can see the google.pdf file, could be a permissions issue. Could you please set 777 permissions to the `/usr/local/bin/wkhtmltopdf` and `/usr/local/bin/wkhtmltoimage` paths? The save the above paths in the Snapshot settings?

**Comment by fdghffdgf** [comment]
This works fine. No Problem.
Permission was already set to 777. It´s right that i install it locally or? Do i have to install wkhtmltopdf on the server?

But thanks for your help!

**Comment by andrelopez** [comment]
Yes, You need to install wkhtmltopdf in your server.

What are you using in your dev environment? vagrant, MAMP, etc?

**Comment by fdghffdgf** [comment]
Than this is the problem. 
I´m sorry. I work with 1&1 and via SSH i get only errors…

**Comment by andrelopez** [comment]
@fdghffdgf You need to install wkhtmltopdf in the server that you're connecting via ssh. We can help with that task send us an email to support@enupal.com.

Best,
