### ISSUE TITLE
Error(s) installing wkhtmltopdf on Vagrant/Homestead

### ISSUE THREAD

**Issue by ademers** [enupal/snapshot#15]
### Description

I'm using Vagrant/Homstead in local dev, Ubuntu 18.04 LTS and when I attempt to install wkhtmltopdf following instructions at https://enupal.com/craft-plugins/enupal-snapshot/docs/getting-started/installation-setup

Error:
```
Err:12 http://packages.blackfire.io/debian any InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 696DBE66A72D76DA
Reading package lists... Done 
E: Repository 'http://ppa.launchpad.net/nginx/development/ubuntu bionic InRelease' changed its 'Label' value from 'NGINX Mainline' to 'NGINX Mainline (1.15.x)'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.blackfire.io/debian any InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 696DBE66A72D76DA
```

Based on a recommendation in the Craft Discord community, I tried https://github.com/JazzCore/python-pdfkit/wiki/Using-wkhtmltopdf-without-X-server

I was then able to add the /usr/local/bin/wkhtmltopdf path. However, I get an error with /usr/local/bin/wkhtmltoimage and /usr/bin/wkhtmltoimage

Craft log:
```
Something went wrong when creating the Image file: The exit status code '127' says something went wrong:
stderr: "sh: 1: /usr/local/bin/wkhtmltoimage: not found
"
stdout: ""
command: "/usr/local/bin/wkhtmltoimage" --format 'jpg' --zoom '1.33' '/home/vagrant/sites/redacted/storage/runtime/temp/enupalsnapshottemp/knp_snappy5c784295e16d40.69144140.html' '/home/vagrant/sites/redacted/storage/runtime/temp/enupalsnapshottemp/public/redacted_TL3QUaQSZO.png'.
```

### Steps to reproduce

1. SSH into Homestead
2. Run commands for Ubuntu 18.04 as described at https://enupal.com/craft-plugins/enupal-snapshot/docs/getting-started/installation-setup

### Additional info

- Craft version: Craft Pro 3.0.29
- PHP version: 7.0.33
- Database driver & version: MySQL 5.5.5
- Plugin version: 1.1.2

**Comment by andrelopez** [comment]
Hi @ademers 

You're only getting this error in the `wkhtmltoimage` ? If so could you please follow the same [instructions](https://github.com/JazzCore/python-pdfkit/wiki/Using-wkhtmltopdf-without-X-server) but for the `wkhtmltoimage` lib?

**Comment by andrelopez** [comment]
Hi @ademers 

Could you please try to follow the next instructions: https://github.com/enupal/snapshot/issues/4#issuecomment-403223479

Install wkhtmltopdf is not required so let's try to download the bin files and add the bin path to the Enupal Snapshot settings

**Comment by ademers** [comment]
Hi @andrelopez,

That worked and my settings were successfully applied as follows:

Absolute Binary Path of wkhtmltopdf lib -> /home/vagrant/wkhtmltox/bin/wkhtmltopdf
/home/vagrant/wkhtmltox/bin/wkhtmltoimage -> /home/vagrant/wkhtmltox/bin/wkhtmltoimage

Thanks!

Would it make sense to update the instructions at https://enupal.com/craft-plugins/enupal-snapshot/docs/getting-started/installation-setup accordingly?

**Comment by andrelopez** [comment]
@ademers  Thanks for following up. I'll update the docs thanks.

**Comment by siebird** [comment]
I'm having the same problem as @ademers. Following the instruction from #4 and the docs. Getting the following error: 

```2019-03-12 06:30:18 [-][1][-][error][enupal\snapshot\Snapshot::error] Something went wrong when creating the PDF file: The exit status code '127' says something went wrong:
stderr: "/home/forge/wkhtmltox/bin/wkhtmltopdf: error while loading shared libraries: libXrender.so.1: cannot open shared object file: No such file or directory
"
stdout: ""
command: "/home/forge/wkhtmltox/bin/wkhtmltopdf" --lowquality --dpi '96' --load-error-handling 'ignore' --zoom '1.33' '/home/forge/domain.com/storage/runtime/temp/enupalsnapshottemp/knp_snappy5c87b46a07ff84.58529647.html' '/home/forge/domain.com/storage/runtime/temp/enupalsnapshottemp/public/AHC_67RW3lONka.pdf'.
2019-03-12 06:30:18 [-][1][-][error][enupal\snapshot\Snapshot::error] Something went wrong when creating the Image file: The exit status code '127' says something went wrong:
stderr: "/home/forge/wkhtmltox/bin/wkhtmltoimage: error while loading shared libraries: libXrender.so.1: cannot open shared object file: No such file or directory
"
stdout: ""
command: "/home/forge/wkhtmltox/bin/wkhtmltoimage" --format 'jpg' --zoom '1.33' '/home/forge/domain.com/storage/runtime/temp/enupalsnapshottemp/knp_snappy5c87b46a0a0590.90277194.html' '/home/forge/domain.com/storage/runtime/temp/enupalsnapshottemp/public/AHC_bnJrVlmJ1h.png'.```
