### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by rachelrine** [enupal/snapshot#17]
### Description
I'm getting frequent errors on PDF generation. 

The logs say "Something went wrong when creating the PDF file: The file `filename.pdf` was not created."

On the front end, I'm wondering if there's a better way to handle the errors. I'm outputting the PDF url, so when it fails, the link is still there it's just broken. 

When I refresh the page, the PDF will generally work. I've increased my php timeout (120s) but the error is still occurring.

What other info might be helpful? Is there a way to better handle front end output when the PDF generation fails?

### Additional info

- Craft version: Craft Pro 3.0.33
- PHP version: 7.0.30
- Database driver & version: MySQL 5.5.5
- Plugin version: 1.1.2
- Using AWS volume for PDF storage

**Comment by andrelopez** [comment]
Hi @rachelrine 

Thanks for reaching out. Sorry for the late reply. You're right it's weird that the link shows the error message we'll fix that in the next release.

To get more info about the error you need to recreate the error and check the next log file:
`storage/logs/web.log`

We can review that log file for you if you want. Please send us an email with the log file to: support@enupal.com

**Comment by rachelrine** [comment]
Sent.

**Comment by andrelopez** [comment]
Hi @rachelrine 

I'll close this issue for now, but you can follow up via email.

Best,
