### ISSUE TITLE
Can't Save Path But Test Does Work/Makes File

### ISSUE THREAD

**Issue by theskyfloor** [enupal/snapshot#18]
### Description

2019-03-29 11:54:16 [-][1][-][error][enupal\snapshot\Snapshot::error] Something went wrong when creating the Image file: The exit status code '1' says something went wrong:
stderr: "Unknown long argument --format

Name:
  wkhtmltopdf 0.12.4 (with patched qt)

Synopsis:
  wkhtmltopdf [GLOBAL OPTION]... [OBJECT]... <output file>
  
Document objects:
  wkhtmltopdf is able to put several objects into the output file, an object is
  either a single webpage, a cover webpage or a table of content.  The objects
  are put into the output document in the order they are specified on the
  command line, options can be specified on a per object basis or in the global
  options area. Options from the Global Options section can only be placed in
  the global options area

  A page objects puts the content of a single webpage into the output document.

  (page)? <input url/file name> [PAGE OPTION]...
  Options for the page object can be placed in the global options and the page
  options areas. The applicable options can be found in the Page Options and 
  Headers And Footer Options sections.

  A cover objects puts the content of a single webpage into the output document,
  the page does not appear in the table of content, and does not have headers
  and footers.

  cover <input url/file name> [PAGE OPTION]...
  All options that can be specified for a page object can also be specified for
  a cover.

  A table of content object inserts a table of content into the output document.

  toc [TOC OPTION]...
  All options that can be specified for a page object can also be specified for
  a toc, further more the options from the TOC Options section can also be
  applied. The table of content is generated via XSLT which means that it can be
  styled to look however you want it to look. To get an aide of how to do this
  you can dump the default xslt document by supplying the
  --dump-default-toc-xsl, and the outline it works on by supplying
  --dump-outline, see the Outline Options section.

Description:
  Converts one or more HTML pages into a PDF document, using wkhtmltopdf patched
  qt.

Global Options:
      --collate                       Collate when printing multiple copies                                      (default)
      --no-collate                    Do not collate when printing multiple                                      copies
      --copies <number>               Number of copies to print into the pdf                                      file (default 1)
  -H, --extended-help                 Display more extensive help, detailing                                      less common command switches
  -g, --grayscale                     PDF will be generated in grayscale
  -h, --help                          Display help
      --license                       Output license information and exit
  -l, --lowquality                    Generates lower quality pdf/ps. Useful to                                      shrink the result document space
  -O, --orientation <orientation>     Set orientation to Landscape or Portrait                                      (default Portrait)
  -s, --page-size <Size>              Set paper size to: A4, Letter, etc.                                      (default A4)
  -q, --quiet                         Be less verbose
      --read-args-from-stdin          Read command line arguments from stdin
      --title <text>                  The title of the generated pdf file (The                                      title of the first document is used if not                                      specified)
  -V, --version                       Output version information and exit
Page Options:
      --print-media-type              Use print media-type instead of screen
      --no-print-media-type           Do not use print media-type instead of                                      screen (default)
Contact:
  If you experience bugs or want to request new features please visit 
  <https://github.com/wkhtmltopdf/wkhtmltopdf/issues>

"
stdout: "

"
command: "/home/theskyfloor/webapps/calc/wkhtmltox/bin/wkhtmltopdf" --format 'jpg' --zoom '1.33' '/home/theskyfloor/webapps/calc/storage/runtime/temp/enupalsnapshottemp/knp_snappy5c9e69d80a5502.19732757.html' '/home/theskyfloor/webapps/calc/storage/runtime/temp/enupalsnapshottemp/public/Visioneering_Feasability_Calculator_65xnb2JSly.png'.

### Steps to reproduce

1.
2.

### Additional info

- Craft version: Latest
- PHP version: 7.2
- Database driver & version: MySQL
- Plugin version: latest

**Comment by theskyfloor** [comment]
I couldn't get this to run no matter what I did... eventually I just erased this from the validation functions:

    if ($object->pdfBinPath && !UrlHelper::isFullUrl($url)) {
            $this->addError($object, $attribute, Snapshot::t('Something went wrong in the test. Please check the path and your logs.'));
        }

And the plug-in now operates as it should. Troubleshooting would be great because this has happened to me in two environments now. Thanks

**Comment by theskyfloor** [comment]
Wondering if `$url = Snapshot::$app->pdf->test() ?? '';` is not populated for some reason?

**Comment by andrelopez** [comment]
Hi @theskyfloor 

Could you please check your `wkhtmltoimage` path setting? It looks like you're saving `wkhtmltopdf` instead of `wkhtmltoimage` in your settings.

`"
stdout: "

"
command: "/home/theskyfloor/webapps/calc/wkhtmltox/bin/wkhtmltopdf" --format 'jpg' --zoom '1.33' '/home/theskyfloor/webapps/calc/storage/runtime/temp/enupalsnapshottemp/knp_snappy5c9e69d80a5502.19732757.html' '/home/theskyfloor/webapps/calc/storage/runtime/temp/enupalsnapshottemp/public/Visioneering_Feasability_Calculator_65xnb2JSly.png'.`

**Comment by theskyfloor** [comment]
Hmm in both environments I have the boxes set correctly and it still errs:

<img width="605" alt="Screen Shot 2019-04-18 at 9 58 41 AM" src="https://user-images.githubusercontent.com/8887839/56370346-a9174380-61c0-11e9-937e-b81a3a3c6b33.png">

**Comment by andrelopez** [comment]
Hi @theskyfloor,

Could you please run the command from your terminal:

/home/theskyfloor/webapps/calc/wkhtmltox/bin/wkhtmltopdf http://google.com google.pdf

What is the output?

**Comment by theskyfloor** [comment]
` /lib/ld-linux.so.2: bad ELF interpreter: No such file or directory`

I gave up on this server though because I found that I was having issues with the library missing some 32-bit extensions and I dont have root access to add them. Now I am running this site on Digital Ocean and was able to add the necessary extensions so it runs without errors but I still can't save the setting without erasing the validation method. Here are those settings:

<img width="524" alt="Screen Shot 2019-04-18 at 9 55 50 AM" src="https://user-images.githubusercontent.com/8887839/56373281-3d37d980-61c6-11e9-9b72-4da9ba8441bf.png">

**Comment by theskyfloor** [comment]
To be clear the logs are clear on save with this server! But I still get the can't save settings error.

**Comment by andrelopez** [comment]
Got it! but we need to know what is the issue on the new server. Could you please run the next command on the digital ocean server?

`/home/forge/m4mquiz.historicdev.com/wkhtmltox/bin/wkhtmltopdf http://google.com google.pdf` 

What is the output?

**Comment by theskyfloor** [comment]
Loading pages (1/6)
QSslSocket: cannot resolve CRYPTO_num_locks                  ] 10%
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv3_client_method
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv3_server_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_library_init
Warning: Failed to load https://ssl.gstatic.com/gb/images/b_8d5afc09.png (ignore)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                      
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback

**Comment by theskyfloor** [comment]
It made the PDF too

**Comment by andrelopez** [comment]
@theskyfloor We just confirmed that the `wkhtmltopdf` lib is working. Could you please check the asset settings that you're using in the `Upload Location` setting and make sure that the next setting is enabled:

`Assets in this volume have public URLs`

**Comment by theskyfloor** [comment]
Ah! That isn't set. Is that a requirement? If so I don't think its noted in the docs anywhere. Tested it and it's working! I see now based on the validation method why it won't save if it cant generate a front-end URL. Should be in the docs or maybe the validator could check for those settings so that it could return an informative error. Thanks for the help!

**Comment by andrelopez** [comment]
@theskyfloor You're right, we'll add a validation to only show Assets with public URL's

You're very welcome 👍
