### ISSUE TITLE
"Asset is missing its folder ID" ERROR when i try to save plugin settings

### ISSUE THREAD

**Issue by piotrpog** [enupal/snapshot#19]
I cannot save plugin settings. When i try, i get "Asset is missing its folder ID" error.

Application Info
PHP version	7.2.1
OS version	WINNT 10.0
Database driver & version	MySQL 5.5.5
Image driver & version	GD 7.2.1
Craft edition & version	Craft Solo 3.1.20.1
Yii version	2.0.16.1
Twig version	2.8.1
Guzzle version	6.3.3
Imagine version	0.7-dev
Plugins
Campaign	1.7.4
Contact Form	2.2.3
Contact Form Extensions	1.1.4
Content Stats	2.1.0
CP Field Inspect	1.0.5
Delete Entry Versions	2.0.0
Entry Instructions	1.0.4
Enupal Snapshot	1.2.3
Enupal Translate	1.2.0
Imager	v2.1.7
Image Resizer	2.0.4
Imager Pretransform	2.0.2
MobileDetect	1.0.2
Position Fieldtype	1.0.14
Queue Manager	1.1.0
Redactor	2.3.2
Retour	3.1.7
SEOmatic	3.1.46
Smart Map	3.2.2
Super Table	2.1.16
Typed link field	1.0.17

**Comment by andrelopez** [comment]
Hi @piotrpog 

Could you please recreate the error and send us a zip file of the next folder: `storage/logs` to support@enupal.com ?

**Comment by piotrpog** [comment]
@andrelopez Just sent.

**Comment by andrelopez** [comment]
The problem was due to the Asset source does not allow pdf extension
