### ISSUE TITLE
Set `wkhtmltopdf` paths using .env values

### ISSUE THREAD

**Issue by lindseydiloreto** [enupal/snapshot#21]
Is it possible to set the binary paths using `.env` values?

<img width="391" alt="Ω 2019-05-30 at 4 29 56 PM" src="https://user-images.githubusercontent.com/5309692/58671695-620c8a00-82f8-11e9-8e10-82657afb33dc.png">

**Comment by lindseydiloreto** [comment]
I actually just did this for the CP CSS plugin. It was very, very easy.

https://github.com/doublesecretagency/craft-cpcss/commit/8631394156bd752ee3f56a673517cde9c3d51e14

Specifically, pay attention to the changes I made in these two files...

 - templates/settings.twig
 - web/assets/CustomAssets.php

**Comment by andrelopez** [comment]
Hi @lindseydiloreto  

Thanks for the example. We just released Enupal Snapshot v1.2.4 with support for environmental variables

**Comment by lindseydiloreto** [comment]
Brilliant, thanks man! 🍺
