### ISSUE TITLE
Can't save settings (even though they are correct)

### ISSUE THREAD

**Issue by lindseydiloreto** [enupal/snapshot#24]
✅ My binary paths are correct.
✅ The test `png` & `pdf` are being generated.
❌ But for some reason, I'm seeing an error message when I try to save settings.

>"Something went wrong in the test. Please check the path and your logs."

When I check the logs, there is nothing indicating an error took place. 🤔 

Let me know if you need additional information!

**Comment by andrelopez** [comment]
Hi @lindseydiloreto 

Could you please confirm that the Asset has the public URL lightswitch enabled in the asset settings?

**Comment by lindseydiloreto** [comment]
Ah, interesting! That's exactly what the problem was. Once I enabled public URLs, I was then able to save the plugin's settings without an error.

Perhaps it's just a messaging issue. I didn't realize that a public URL was required.
