### ISSUE TITLE
Spanish pages in docs

### ISSUE THREAD

**Issue by lindseydiloreto** [enupal/snapshot#25]
Some docs pages are in Spanish?

https://enupal.com/craft-plugins/enupal-snapshot/docs/image-examples/generate-an-image-from-html
https://enupal.com/craft-plugins/enupal-snapshot/docs/image-examples/image-lib-options

**Comment by andrelopez** [comment]
Thanks @lindseydiloreto, fixed!

**Comment by lindseydiloreto** [comment]
Great, no problem! 🙂
