### ISSUE TITLE
Settings not saving when using multi environment conig

### ISSUE THREAD

**Issue by shornuk** [enupal/snapshot#26]
### Description

Installed plugin, set up and working nicely. Created a `snapshot.php` file in the `config` folder. Added bin paths for the relevant environments, but the settings just don't save and nothing added to the `snapshot.php` file is getting through to the plugin.

- Craft version: 3.1.30
- Plugin version: Latest

**Comment by andrelopez** [comment]
Hi @shornuk 

We just released Enupal Snapshot v1.2.4 with support for [environmental values](https://docs.craftcms.com/v3/config/environments.html) please let us know if that would work.
