### ISSUE TITLE
PDF Fails when passing margin-top as cliOption

### ISSUE THREAD

**Issue by gdubois414** [enupal/snapshot#27]
### Description
I keep getting this error in the log: Something went wrong when creating the PDF file: The option 'margin-top ' does not exist.

My code is as follows:
```
{%
  set settings = {
            filename: 'quote' ~ entry.quoteNumber ~ '.pdf',
            cliOptions: {
                'footer-html': 'quotes/_pdf-footer.html',
                'margin-top': '30'
            }
  }
%}

    {{ craft.enupalsnapshot.displayHtml(html, settings) }}
```

I have tried using an integer, string, and including px in the margin-top value. Removing that option fixes the problem.

### Steps to reproduce

1. Add 'margin-top' to cliOptions
2. Go to url of the pdf

### Additional info

- Craft version: 3.1.31
- PHP version: 7.2.14
- Plugin version: 1.2.4

**Comment by andrelopez** [comment]
The error was due to extra space in the `'margin-top '` key
