### ISSUE TITLE
PDF Not Rendering when devMode = false

### ISSUE THREAD

**Issue by davist11** [enupal/snapshot#29]
### Description
We are in the process of updating Craft to 3.1 and updating plugins to go along with it. This PDF rendered fine before, but now, the PDF will not render if `devMode` is set to `false`. The PDF works fine in my local environment (where `devMode` is `true`), but once deployed to staging, where it's `false` I get the following:

![image](https://user-images.githubusercontent.com/199985/61005578-73ed3e00-a336-11e9-93eb-a3cd43e67d4f.png)

If I flip that config to `true` it renders fine.

### Additional info

- Craft version: Craft Pro 3.1.34
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.26
- Plugin version: 1.2.5

**Comment by okay-type** [comment]
I have the same problem.

**Comment by andrelopez** [comment]
Thanks. I'm on it

**Comment by andrelopez** [comment]
Hi @davist11 @okay-type 

We just released Enupal Snapshot v1.2.6 with a fix to this issue, could you please update the plugin and let us know if the issue is fixed?

Best,

**Comment by davist11** [comment]
Yup, looks like that fixed it. Thanks for the quick fix!

**Comment by bymayo** [comment]
I'm getting this issue, even when I've updated v.1.2.6

Craft Pro 3.3.3
Enupal Snapshop 1.2.6
PHP 7.0.33
