### ISSUE TITLE
Cannot save settings. Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by stphnmartin** [enupal/snapshot#30]
### Description
I've followed the installation instructions for Ubuntu and installed Wkhtmltopdf, however, I cannot save the settings with the correct paths in the CP settings. I receive a "Couldn't save plugin settings." error message. There is nothing in the error logs indicating there is a problem. I read another tix with this similar problems saying to make sure assets have a public URL and they do.

The plugin works on my development server, but not in production using the same Ubuntu server.

### Steps to reproduce

1. Enter correct paths into CP Enupal Snapshot fields.
2. Click enter

### Additional info

- Craft version:
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.26
- Plugin version: 1.2.6

**Comment by andrelopez** [comment]
Hi @stphnmartin 

We may need more info to help out. Could you please send us a zip file of the following folder?

`storage/logs`

Please send the file to support@enupal.com

**Comment by stphnmartin** [comment]
I will email them. I've sent them previously.

**Comment by stphnmartin** [comment]
Just sent log files.

**Comment by andrelopez** [comment]
The error was:

`Something went wrong when creating the PDF file: The exit status code '127' says something went wrong:
stderr: "/storage/av06309/wkhtmltox/bin/wkhtmltopdf: error while loading shared libraries: libXrender.so.1: cannot open shared object file`

And was solved running the following in the server:

`sudo apt-get install libxrender1`
