### ISSUE TITLE
504 Gateway Time-out on saving settings

### ISSUE THREAD

**Issue by mdunbavan** [enupal/snapshot#31]
### Description
Issue we are facing is that when we save the plugin settings, nothing happens and it times out.

### Steps to reproduce

1. Install wkhtmltopdf packages locally
2. Install plugin
3. Activate plugin
4. Go to settings and save

### Additional info

- Craft version: 3.2.9
- PHP version: 7.3
- Database driver & version:
- Plugin version: 1.2.6

**Comment by andrelopez** [comment]
Hi @mdunbavan Could you please recreate this issue and send back to us a zip file of the following folder?
`storage/logs`

Please send the file to support@enupal.com

**Comment by andrelopez** [comment]
I'm going to close this ticket due to no response. Feel free to reopen if still getting this issue
