### ISSUE TITLE
override setting does not work

### ISSUE THREAD

**Issue by aquafun** [enupal/snapshot#35]
### Description

if you try to generate a pdf with  following configuration:
`{%
	set settings = {
		filename: 'my-first-pdf.pdf',
		inline: false,
		overrideFile: false
	}
%}`

it still regenerate the pdf even when the file exists. 

### Steps to reproduce

1. generate a pdf with the option `overrideFile:false`
2. now reload the page
3. still generating the pdf

### Additional info

- Craft version: 3.3.15
- PHP version: 7.3.9
- Database driver & version: MySQL 5.7.27
- Plugin version: 1.2.6

**Comment by andrelopez** [comment]
Hi @aquafun we just released v1.2.7 with a fix to this problem. Thank you
