### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by darylknight** [enupal/snapshot#36]
On the (requirements)[https://docs.enupal.com/enupal-snapshot/getting-started/requirements.html] page in the docs, there's a link for how to install wkhtmltopdf. That link just takes you back to the Installation of the plugin page.

It appears to link to 
https://enupal.com/craft-plugins/enupal-snapshot/docs/getting-started/installation-setup#entry:2491:url which is either broken or a redirect.

**Comment by andrelopez** [comment]
Hi @darylknight fixed! https://docs.enupal.com/enupal-snapshot/getting-started/installation-setup.html#install-wkhtmltopdf-on-ubuntu-via-command-line

Thanks for reporting
