### ISSUE TITLE
Unable to find the template

### ISSUE THREAD

**Issue by luizhv** [enupal/snapshot#37]
### Description

I'm using snapshot alongside stripe payments and when I try to view an order I get this error no matter what template path I use.

![Screenshot 2020-06-26 at 5 04 36 PM](https://user-images.githubusercontent.com/1696285/85822966-50820400-b7d0-11ea-98cf-a09e358ee15e.png)

### Steps to reproduce

1. Click to view the order 

### Additional info

- Craft version: Craft Solo 3.4.25
- PHP version: 7.4.7
- Database driver & version: MySQL 5.7.29
- Plugin version: Enupal Snapshot 1.27 
- Plugin version: Stripe Payments 2.7.2

**Comment by andrelopez** [comment]
@luizhv I was able to recreate this issue and I'll let you know once is fixed

**Comment by andrelopez** [comment]
Hi @luizhv We just released Enupal Snapshot v1.2.8 with a fix to this problem. Thanks for reporting
