### ISSUE TITLE
Can't save binary paths even when assets in this volume have public URLs is set

### ISSUE THREAD

**Issue by Graphetal** [enupal/snapshot#40]
### Description

I'm not able to save the setting in Enupal Snapshot after placing valid paths. Getting the "Something went wrong in the test. Please check the path and your logs" error. I've confirmed that the upload destination is to a volume where "Assets in this volume have public URLs" was set. Also, I've run a test (http://google.com google.pdf) and everything is fine.

### Steps to reproduce

1. Added binary path for image and pdf
2. Selected public volume

### Additional info

- Craft version: Craft Solo 3.5.14
- PHP version: 7.3.23
- Database driver & version: MySQL 10.3.23
- Plugin version: 1.2.8
<img width="1673" alt="Screen Shot 2020-11-03 at 12 57 10 PM" src="https://user-images.githubusercontent.com/63877813/98039847-35557f80-1dd4-11eb-8e30-ee169451328e.png">

**Comment by andrelopez** [comment]
Hi @Graphetal could you please send back to us a zip file of the storage/logs folder to support@enupal.com?

In the meantime could you please check that your Volume (Settings -> Assets -> Volumes) has the next setting enabled? 
`Assets in this volume have public URLs`

Also, that has a valid URL HTTP or HTPPS (relative URL's are not supported)

**Comment by Graphetal** [comment]
Well looks like I'm an idiot :)

Turns out I forgot to include a forward slash in the Base URL which was generating a broken link (thus not a valid URL)

Thanks for the quick response!
