### ISSUE TITLE
Ubuntu 20.04 installation - error loading resources by https

### ISSUE THREAD

**Issue by mmc501** [enupal/snapshot#42]
### Description
I have installed the plugin all was working fine when on staging with non ssl url.
When I put the site live and enabled the ssl the pdf generation no longer works.

I get the error: 

Exit with code 1 due to network error: UnknownNetworkError
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback

I saw in the docs this is required for Ubuntu 18.04
$ sudo apt-get install libssl1.0-dev
$ sudo apt-get install libxrender1

libssl-dev is already installed.
libxrender1 is already installed

I tried to install libssl1.0-dev but it said it was not available.  

How can i resolve this issue?

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.5.14
- PHP version: 7.4
- Plugin version: 1.2.8

**Comment by andrelopez** [comment]
This issue is solved by installing wkhtmltopf v0.12.6, instructions here: https://docs.enupal.com/enupal-snapshot/getting-started/installation-setup.html#ubuntu-20-04-x64

Thanks for reporting @mmc501
