### ISSUE TITLE
snapshot not accepting to path to wkhtmltopdf + nitro

### ISSUE THREAD

**Issue by paulmendrik** [enupal/snapshot#43]
Hi Andre,

Sorry to bother you again, but I don't seems to get snapshot to accept the path to path to wkhtmltopdf ev en though I've followed the instructions exactly wkhtmltopdf is installed on the server, when I use the command pwd, I get /home/ploi/wkhtmltox/bin 'ploi' being my server name but adding this path  with /wkhtmltopdf or /wkhtmltoimage gives me an error Something went wrong in the test. Please check the path and your logs.and cannot be saved to the settings. 
I'm not sure what I'm doing wrong here, so can you help ?

Thanks again,

Paul

**Comment by andrelopez** [comment]
Hi @paulmendrik np, could you please recreate the error and send back to us a zip file of the following folder? storage/logs

Please send the file to support@enupal.com

**Comment by shoored** [comment]
@paulmendrik Did you get this resolved? I got in touch with the same issue regarding a local Craft Nitro setup.

**Comment by mmc501** [comment]
@shoored I had a similar issue a few days ago.  Does the Upload Location in the Enupal Settings have a public URLs enabled?
If that's not enabled it doesn't seem to save.
I've been trying to have the pdf's generated in a secure folder location but have been unsuccessful so far.

**Comment by chocolayin** [comment]
I'm having the same issue with local Craft Nitro too. Any solution? The plugin doesn't accept the path provided.

**Comment by mmc501** [comment]
> I'm having the same issue with local Craft Nitro too. Any solution? The plugin doesn't accept the path provided.

I found the issue in my case was that the volume which was selected in the Upload Location below where you enter the path needs to have public url's enabled.

**Comment by chocolayin** [comment]
> > I'm having the same issue with local Craft Nitro too. Any solution? The plugin doesn't accept the path provided.
> 
> I found the issue in my case was that the volume which was selected in the Upload Location below where you enter the path needs to have public url's enabled.

I have enabled it. But still not working.

**Comment by andrelopez** [comment]
@chocolayin could you please recreate the error and send back to us a zip file of the following folder? storage/logs 

Please send the file to support@enupal.com

**Comment by chocolayin** [comment]
> @chocolayin could you please recreate the error and send back to us a zip file of the following folder? storage/logs
> 
> Please send the file to [support@enupal.com](mailto:support@enupal.com)

Sure, I have sent the logs file.

**Comment by johnwbaxter** [comment]
@andrelopez Same problem here, it doesn't work in Craft Nitro. Do you have any updates on this?

**Comment by johnwbaxter** [comment]
@andrelopez  This is the relevant log text

```
2021-09-09 12:02:50 [-][1][-][error][enupal\snapshot\Snapshot::error] Something went wrong when creating the Image file: The exit status code '127' says something went wrong:
stderr: "sh: /app/vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64: not found
"
stdout: ""
command: "/app/vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64" --format 'jpg' --zoom '1.33' '/app/storage/runtime/temp/enupalsnapshottemp/knp_snappy6139e9dad95477.82174487.html' '/app/storage/runtime/temp/enupalsnapshottemp/public/Choice_NzpEGEqdoJ.png'.
```

The files are all there though.

**Comment by johnwbaxter** [comment]
@andrelopez Any chance of you taking a look at this? It's been quite a while now....

**Comment by andrelopez** [comment]
I was able to recreate this issue on [nitro](https://craftcms.com/docs/nitro/2.x/), the issue is due that the ubuntu packages are not supported on Alpine (nitro linux distribution)
I have tried installing the `wkhtmltopdf` available on Alpine packages but it looks like is missing some dependencies
```batch
// first login as root to nitro
nitro ssh your_container --root 

// then install wkhtmltopdf
apk add --no-cache wkhtmltopdf
```

I will back when I find a fix to this issue

**Comment by johnwbaxter** [comment]
Ok, thank you very much for looking into it @andrelopez !!

**Comment by andrelopez** [comment]
Hi @johnwbaxter could you please try to install wkhtmltopdf following the next instructions?
- Open your terminal
- Login to nitro vi ssh as root:
`nitro ssh your_container --root `
- Install wkhtmltopf
`apk add --no-cache wkhtmltopdf`
- Install dependencies, paste each line one by one, and hit enter:
```bash
apk add so:libQt5Core.so.5 
apk add so:libQt5Gui.so.5 
apk add so:libQt5Network.so.5 
apk add so:libQt5PrintSupport.so.5 
apk add so:libQt5Svg.so.5 
apk add so:libQt5WebKit.so.5
apk add so:libQt5WebKitWidgets.so.5
apk add so:libQt5Widgets.so.5
apk add so:libc.musl-x86_64.so.1
apk add so:libgcc_s.so.1
apk add so:libstdc++.so.6
```
- If you want to exit:
`exit`
- On your Craft CMS dashboard go to the Enupal Snapshot settings and save the following settings:
Absolute Binary Path of wkhtmltopdf libRequired:
`/usr/bin/wkhtmltopdf`

Absolute Binary Path of wkhtmltoimage lib
`/usr/bin/wkhtmltoimage`

- Make sure your Upload Location asset has the `Assets in this volume have public URLs` setting enabled
- Save the settings 

Please let me know if that works, it's working on my side.

**Comment by andrelopez** [comment]
@johnwbaxter thanks for following up. Could you please login as root via ssh again and run the following command and hit enter:
```bash
apk --update --no-cache add \
   wkhtmltopdf \
    libgcc \
    libstdc++ \
    musl \
    qt5-qtbase \
    qt5-qtbase-x11 \
    qt5-qtsvg \
    qt5-qtwebkit \
    ttf-freefont \
    ttf-dejavu \
    ttf-droid \
    ttf-liberation \
    fontconfig
 ```
Let me know if that works

**Comment by johnwbaxter** [comment]
@andrelopez That works!!!!!

**Comment by andrelopez** [comment]
@johnwbaxter great! will update the docs soon. Thank you!

**Comment by johnwbaxter** [comment]
@andrelopez Awesome, thanks Andre!!!

**Comment by andrelopez** [comment]
In summary, to install Enupal Snapshot on Nitro 2 (may be the same for Alpine Linux distros)
- Login to nitro via ssh as root:
`nitro ssh your_nitro_site_name --root`
- Run the following command to install `wkhtmltopdf` and dependencies
```
apk --update --no-cache add \
   wkhtmltopdf \
    libgcc \
    libstdc++ \
    musl \
    qt5-qtbase \
    qt5-qtbase-x11 \
    qt5-qtsvg \
    qt5-qtwebkit \
    ttf-freefont \
    ttf-dejavu \
    ttf-droid \
    ttf-liberation \
    fontconfig \
    so:libQt5Core.so.5 \
    so:libQt5Gui.so.5 \
    so:libQt5Network.so.5 \
    so:libQt5PrintSupport.so.5 \
    so:libQt5Svg.so.5 \
    so:libQt5WebKit.so.5\
    so:libQt5WebKitWidgets.so.5\
    so:libQt5Widgets.so.5\
    so:libc.musl-x86_64.so.1\
    so:libgcc_s.so.1\
    so:libstdc++.so.6
```

- On your Craft CMS dashboard go to the Enupal Snapshot settings and save the following settings:
Absolute Binary Path of wkhtmltopdf libRequired:
`/usr/bin/wkhtmltopdf`

Absolute Binary Path of wkhtmltoimage lib
`/usr/bin/wkhtmltoimage`

- Save your Settings
