### ISSUE TITLE
Trouble with Paths in local development

### ISSUE THREAD

**Issue by bphippen** [enupal/snapshot#5]
### Description
Hi, I am having trouble getting the correct paths on my local development server. 

I am using Local by Flywheel as a local dev environment and even though made for WP works great for Craft.

I am not extremely familiar with how they make it work, but I know they use docker containers but unsure of the linux OS.

I have SSH'd into the container and tried the command line instructions but that also didn't seem to work.

I also installed wkhtmltopdf as a mac package and the bin files are located in /usr/local/bin/ ...but no go there too.

Looked into the logs and this is what I am getting: error while loading shared libraries: libXrender.so.1: cannot open shared object file: No such file or directory

Any ideas?

Thanks in advance for your help,
Brennen

### Steps to reproduce

1. Load Craft within a Local by Flywheel environment
2. Paste in paths

### Additional info

- Craft version: 3.0.18
- PHP version: 7.1.4
- Database driver & version: 5.5.55
- Plugin version: 1.0.4

**Comment by bphippen** [comment]
Installed 3 more libraries and it seems to work now.

apt-get install libxrender1
apt-get install libfontconfig1
apt-get install libxext6

**Comment by andrelopez** [comment]
Hi @bphippen 

Thanks for the update. I'll add this to the docs.

Best,
