### ISSUE TITLE
How to disable integration with Enupal Stripe payments?

### ISSUE THREAD

**Issue by mark-chief** [enupal/snapshot#59]
### Description
Hello, I am using Enupal Snapshot to generate PDF's across my site. But it is automatically attaching a PDF to each Stripe order confirmation email in Enupal Payments. How can I disable attaching the order pdf to an order confirmation?

### Additional info

- Craft version: 3.7.36
- PHP version: 7.4
- Database driver & version:
- Plugin version: 4.1.1

**Comment by mark-chief** [comment]
Hello @andrelopez , are you able to help with this? The PDF's are just not working for me at the moment (see my other thread) so I just need to prevent from from being sent out on order confirmation emails now. Thanks again for your help.

**Comment by andrelopez** [comment]
Hi @mark-chief We just released Snapshot v2.0.2 for Craft4 and v1.2.10 for Craft3 with a new setting to disable this workflow. Please go to Plugins -> Enupal Snapshot -> Settings and disable `Enable PDF attachment on Stripe Payments Order email`
